{
  "success": false,
  "return_code": 1,
  "stdout": "",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_20_2025/backtests_final/ExtremeDivergence_BTFinal_v1.py\", line 137, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1170, in run\n    strategy.next()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_20_2025/backtests_final/ExtremeDivergence_BTFinal_v1.py\", line 32, in next\n    if self.i < 10:\nAttributeError: 'ExtremeDivergence' object has no attribute 'i'. Did you mean: 'I'?\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_v3/10_20_2025/backtests_final/ExtremeDivergence_BTFinal_v1.py` failed. (See above for error)\n",
  "execution_time": 1.38831,
  "timestamp": "2025-10-20T10:14:09.497851"
}